In [127]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import tree
import numpy as np
import pandas as pd
from sklearn import metrics

In [128]:
data = pd.read_csv('/home/dominik/Dokumenty/Studia/Data-mining/Lista5-trees/cars.data',names=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'])
data.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [129]:
np.any(data.isnull())

False

In [130]:
for name in data.columns.values:
    data[name] = pd.Categorical(data[name]).codes

data.head()

buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

In [131]:
mask = np.random.uniform(0,1, len(data))
train_data = data[mask <= 0.7]
test_data = data[mask > 0.7]

y = train_data['class']
X = train_data.drop('class', axis=1)
print(X.shape)

t = tree.DecisionTreeClassifier()
t = t.fit(X,y)

y = test_data['class']
X = test_data.drop('class', axis=1)
print(X.shape)


t.score(X,y)

(1186, 6)
(542, 6)


0.96125461254612543

In [132]:
importances = t.tree_.compute_feature_importances()
importances

array([ 0.23925599,  0.15834928,  0.05330869,  0.19374095,  0.09849719,
        0.2568479 ])

In [133]:
clearMask = [i+1 for i in range(len(importances)) if importances[i] < 0.04]
clearedData = data.drop(data.columns.values[clearMask],axis=1)

In [134]:
mask = np.random.uniform(0,1, len(clearedData))
train_data = clearedData[mask <= 0.7]
test_data = clearedData[mask > 0.7]

y = train_data['class']
X = train_data.drop('class', axis=1)
print(X.shape)

t = tree.DecisionTreeClassifier(max_depth=10, min_samples_split=6)
t = t.fit(X,y)

y = test_data['class']
X = test_data.drop('class', axis=1)
print(X.shape)


t.score(X,y)

(1225, 6)
(503, 6)


0.95029821073558651

In [135]:
confusion_matrix = metrics.confusion_matrix(y, t.predict(X))
print ("Confusion Matrix\n", confusion_matrix)

Confusion Matrix
 [[100   9   4   2]
 [  0  16   0   0]
 [  7   0 346   0]
 [  0   3   0  16]]


In [136]:
from sklearn.metrics import classification_report
print(classification_report(y, 
                            t.predict(X), 
                            target_names=['unacc', 'acc', 'good', 'v-good']))

             precision    recall  f1-score   support

      unacc       0.93      0.87      0.90       115
        acc       0.57      1.00      0.73        16
       good       0.99      0.98      0.98       353
     v-good       0.89      0.84      0.86        19

avg / total       0.96      0.95      0.95       503



In [137]:
mask = np.random.uniform(0,1, len(clearedData))
train_data = clearedData[mask <= 0.7]
test_data = clearedData[mask > 0.7]

y = train_data['class']
X = train_data.drop('class', axis=1)
print(X.shape)

f = RandomForestClassifier()
f = f.fit(X,y)

y = test_data['class']
X = test_data.drop('class', axis=1)
print(X.shape)


f.score(X,y)

(1217, 6)
(511, 6)


0.95694716242661448

In [138]:
confusion_matrix = metrics.confusion_matrix(y, f.predict(X))
print ("Confusion Matrix\n", confusion_matrix)

Confusion Matrix
 [[100   4  10   1]
 [  1  13   0   0]
 [  4   0 352   0]
 [  2   0   0  24]]


In [139]:
print(classification_report(y, 
                            f.predict(X), 
                            target_names=['unacc', 'acc', 'good', 'v-good']))

             precision    recall  f1-score   support

      unacc       0.93      0.87      0.90       115
        acc       0.76      0.93      0.84        14
       good       0.97      0.99      0.98       356
     v-good       0.96      0.92      0.94        26

avg / total       0.96      0.96      0.96       511



In [140]:
mask = np.random.uniform(0,1, len(clearedData))
train_data = clearedData[mask <= 0.7]
test_data = clearedData[mask > 0.7]

y = train_data['class']
X = train_data.drop('class', axis=1)
print(X.shape)

f = ExtraTreesClassifier(max_depth=10, min_samples_split=8)
f = f.fit(X,y)

y = test_data['class']
X = test_data.drop('class', axis=1)
print(X.shape)


f.score(X,y)

(1159, 6)
(569, 6)


0.91915641476274168

In [141]:
confusion_matrix = metrics.confusion_matrix(y, f.predict(X))
print ("Confusion Matrix\n", confusion_matrix)

Confusion Matrix
 [[115   0  20   0]
 [ 17   5   1   2]
 [  6   0 387   0]
 [  0   0   0  16]]


In [142]:
print(classification_report(y, 
                            f.predict(X), 
                            target_names=['unacc', 'acc', 'good', 'v-good']))

             precision    recall  f1-score   support

      unacc       0.83      0.85      0.84       135
        acc       1.00      0.20      0.33        25
       good       0.95      0.98      0.97       393
     v-good       0.89      1.00      0.94        16

avg / total       0.92      0.92      0.91       569



In [143]:
clearedData['train'] = np.random.uniform(0, 1, len(clearedData))
err = 0
for i in range(10):
    data_test = clearedData[(clearedData['train'] >= i*0.1) & (clearedData['train'] < (i+1)*0.1)]
    data_train = clearedData[(clearedData['train'] < i*0.1) | (clearedData['train'] >= (i+1)*0.1)]

    y = data_train['class']
    X = data_train.drop('class', axis = 1).drop('train',axis=1)

    t = tree.DecisionTreeClassifier(max_depth=10, min_samples_split=6)
    t = t.fit(X, y)
#     print('depth', [i.tree_.max_depth for i in t.estimators_])
    y = data_test['class']
    X = data_test.drop('class', axis = 1).drop('train',axis=1)
    print(t.score(X,y))
    err += t.score(X,y) / 10

print('Average score: ',err)

0.956043956044
0.964071856287
0.951219512195
0.938271604938
0.965714285714
0.949152542373
0.97191011236
0.939393939394
0.941860465116
0.967741935484
Average score:  0.954538020991


In [144]:
clearedData['train'] = np.random.uniform(0, 1, len(clearedData))
err = 0
for i in range(10):
    data_test = clearedData[(clearedData['train'] >= i*0.1) & (clearedData['train'] < (i+1)*0.1)]
    data_train = clearedData[(clearedData['train'] < i*0.1) | (clearedData['train'] >= (i+1)*0.1)]

    y = data_train['class']
    X = data_train.drop('class', axis = 1).drop('train',axis=1)

    f = RandomForestClassifier()
    f = f.fit(X, y)
#     print('depth', [i.tree_.max_depth for i in t.estimators_])
    y = data_test['class']
    X = data_test.drop('class', axis = 1).drop('train',axis=1)
    print(f.score(X,y))
    err += f.score(X,y) / 10

print('Average score: ',err)

0.932584269663
0.965317919075
0.957831325301
0.980487804878
0.98224852071
0.962732919255
0.963855421687
0.93023255814
0.977777777778
0.943037974684
Average score:  0.959610649117


In [145]:
data['train'] = np.random.uniform(0, 1, len(clearedData))
err = 0
for i in range(10):
    data_test = clearedData[(clearedData['train'] >= i*0.1) & (clearedData['train'] < (i+1)*0.1)]
    data_train = clearedData[(clearedData['train'] < i*0.1) | (clearedData['train'] >= (i+1)*0.1)]

    y = data_train['class']
    X = data_train.drop('class', axis = 1).drop('train',axis=1)

    f = ExtraTreesClassifier()
    f = f.fit(X, y)
#     print('depth', [i.tree_.max_depth for i in t.estimators_])
    y = data_test['class']
    X = data_test.drop('class', axis = 1).drop('train',axis=1)
    print(f.score(X,y))
    err += f.score(X,y) / 10

print('Average score: ',err)

0.943820224719
0.947976878613
0.969879518072
0.965853658537
0.952662721893
0.931677018634
0.951807228916
0.953488372093
0.927777777778
0.924050632911
Average score:  0.946899403217
