In [76]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import tree
import numpy as np
import pandas as pd
from sklearn import metrics

In [77]:
data = pd.read_csv('/home/dominik/Dokumenty/Studia/Data-mining/Lista5-trees/mushroom.data', names=['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises?', 'odor', 'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color', 'stalk-shape', 'stalk-root', 'stalk-surface-above-ring', 'stalk-surface-below-ring', 'stalk-color-above-ring', 'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number', 'ring-type', 'spore-print-color', 'population', 'habitat'])
data.head()

class cap-shape cap-surface cap-color bruises? odor gill-attachment  \
0     p         x           s         n        t    p               f   
1     e         x           s         y        t    a               f   
2     e         b           s         w        t    l               f   
3     p         x           y         w        t    p               f   
4     e         x           s         g        f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [78]:
data = data.drop('stalk-root',axis=1)

In [79]:
data.head()

class cap-shape cap-surface cap-color bruises? odor gill-attachment  \
0     p         x           s         n        t    p               f   
1     e         x           s         y        t    a               f   
2     e         b           s         w        t    l               f   
3     p         x           y         w        t    p               f   
4     e         x           s         g        f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 22 columns]

In [80]:
for name in data.columns.values:
    data[name] = pd.Categorical(data[name]).codes

In [81]:
data.head()

class  cap-shape  cap-surface  cap-color  bruises?  odor  gill-attachment  \
0      1          5            2          4         1     6                1   
1      0          5            2          9         1     0                1   
2      0          0            2          8         1     3                1   
3      1          5            3          8         1     6                1   
4      0          5            2          3         0     5                1   

   gill-spacing  gill-size  gill-color   ...     stalk-surface-below-ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 22 columns]

In [82]:
mask = np.random.uniform(0,1, len(data))
train_data = data[mask <= 0.7]
test_data = data[mask > 0.7]

y = train_data['class']
X = train_data.drop('class', axis=1)
print(X.shape)

t = tree.DecisionTreeClassifier()
t = t.fit(X,y)

y = test_data['class']
X = test_data.drop('class', axis=1)
print(X.shape)


t.score(X,y)

(5679, 21)
(2445, 21)


1.0

In [83]:
mask = np.random.uniform(0,1, len(data))
train_data = data[mask <= 0.7]
test_data = data[mask > 0.7]

y = train_data['class']
X = train_data.drop('class', axis=1)
print(X.shape)

f = RandomForestClassifier()
f = f.fit(X,y)

y = test_data['class']
X = test_data.drop('class', axis=1)
print(X.shape)


f.score(X,y)

(5635, 21)
(2489, 21)


1.0

In [84]:
importances = t.tree_.compute_feature_importances()
importances

array([ 0.        ,  0.        ,  0.00288278,  0.03096103,  0.03933153,
        0.        ,  0.        ,  0.13083826,  0.34520773,  0.0247394 ,
        0.        ,  0.0016789 ,  0.01766801,  0.        ,  0.        ,
        0.        ,  0.00099074,  0.        ,  0.20043215,  0.17918022,
        0.02608925])

In [85]:
clearMask = [i+1 for i in range(len(importances)) if importances[i] < 0.01]
clearedData = data.drop(data.columns.values[clearMask],axis=1)

In [86]:
mask = np.random.uniform(0,1, len(clearedData))
train_data = clearedData[mask <= 0.7]
test_data = clearedData[mask > 0.7]

y = train_data['class']
X = train_data.drop('class', axis=1)
print(X.shape)

t = tree.DecisionTreeClassifier()
t = t.fit(X,y)

y = test_data['class']
X = test_data.drop('class', axis=1)
print(X.shape)


t.score(X,y)

(5734, 9)
(2390, 9)


1.0

In [87]:
confusion_matrix = metrics.confusion_matrix(y, t.predict(X))
print ("Confusion Matrix\n", confusion_matrix)

Confusion Matrix
 [[1229    0]
 [   0 1161]]


In [88]:
t.tree_.compute_feature_importances()

array([ 0.02500292,  0.03621673,  0.12555256,  0.34716487,  0.02355143,
        0.0181541 ,  0.21511715,  0.17839095,  0.0308493 ])

In [89]:
mask = np.random.uniform(0,1, len(clearedData))
train_data = clearedData[mask <= 0.7]
test_data = clearedData[mask > 0.7]

y = train_data['class']
X = train_data.drop('class', axis=1)
print(X.shape)

f = RandomForestClassifier()
f = f.fit(X,y)

y = test_data['class']
X = test_data.drop('class', axis=1)
print(X.shape)


f.score(X,y)

(5707, 9)
(2417, 9)


1.0

In [90]:
confusion_matrix = metrics.confusion_matrix(y, f.predict(X))
print ("Confusion Matrix\n", confusion_matrix)

Confusion Matrix
 [[1269    0]
 [   0 1148]]


In [91]:
data['train'] = np.random.uniform(0, 1, len(data))
err = 0
for i in range(10):
    data_test = data[(data['train'] >= i*0.1) & (data['train'] < (i+1)*0.1)]
    data_train = data[(data['train'] < i*0.1) | (data['train'] >= (i+1)*0.1)]

    y = data_train['class']
    X = data_train.drop('class', axis = 1).drop('train',axis=1)

    t = tree.DecisionTreeClassifier()
    t = t.fit(X, y)
#     print('depth', [i.tree_.max_depth for i in t.estimators_])
    y = data_test['class']
    X = data_test.drop('class', axis = 1).drop('train',axis=1)
    print(t.score(X,y))
    confusion_matrix = metrics.confusion_matrix(y, t.predict(X))
    print ("Confusion Matrix\n", confusion_matrix)
    err += t.score(X,y) / 10

print('Average score: ', err)

1.0
Confusion Matrix
 [[445   0]
 [  0 391]]
1.0
Confusion Matrix
 [[384   0]
 [  0 396]]
1.0
Confusion Matrix
 [[432   0]
 [  0 416]]
1.0
Confusion Matrix
 [[386   0]
 [  0 393]]
1.0
Confusion Matrix
 [[423   0]
 [  0 401]]
1.0
Confusion Matrix
 [[426   0]
 [  0 394]]
1.0
Confusion Matrix
 [[412   0]
 [  0 356]]
1.0
Confusion Matrix
 [[433   0]
 [  0 389]]
1.0
Confusion Matrix
 [[431   0]
 [  0 408]]
1.0
Confusion Matrix
 [[436   0]
 [  0 372]]
Average score:  1.0


In [92]:
data['train'] = np.random.uniform(0, 1, len(data))
err = 0
for i in range(10):
    data_test = data[(data['train'] >= i*0.1) & (data['train'] < (i+1)*0.1)]
    data_train = data[(data['train'] < i*0.1) | (data['train'] >= (i+1)*0.1)]

    y = data_train['class']
    X = data_train.drop('class', axis = 1).drop('train',axis=1)

    f = RandomForestClassifier()
    f = f.fit(X, y)
#     print('depth', [i.tree_.max_depth for i in t.estimators_])
    y = data_test['class']
    X = data_test.drop('class', axis = 1).drop('train',axis=1)
    print(f.score(X,y))
    confusion_matrix = metrics.confusion_matrix(y, f.predict(X))
    print ("Confusion Matrix\n", confusion_matrix)
    err += f.score(X,y) / 10

print('Average score: ',err)

1.0
Confusion Matrix
 [[444   0]
 [  0 365]]
1.0
Confusion Matrix
 [[427   0]
 [  0 401]]
1.0
Confusion Matrix
 [[436   0]
 [  0 375]]
1.0
Confusion Matrix
 [[392   0]
 [  0 425]]
1.0
Confusion Matrix
 [[438   0]
 [  0 361]]
1.0
Confusion Matrix
 [[394   0]
 [  0 399]]
1.0
Confusion Matrix
 [[413   0]
 [  0 383]]
1.0
Confusion Matrix
 [[419   0]
 [  0 397]]
1.0
Confusion Matrix
 [[428   0]
 [  0 427]]
1.0
Confusion Matrix
 [[417   0]
 [  0 383]]
Average score:  1.0


In [93]:
clearedData['train'] = np.random.uniform(0, 1, len(clearedData))
err = 0
for i in range(10):
    data_test = clearedData[(clearedData['train'] >= i*0.1) & (clearedData['train'] < (i+1)*0.1)]
    data_train = clearedData[(clearedData['train'] < i*0.1) | (clearedData['train'] >= (i+1)*0.1)]

    y = data_train['class']
    X = data_train.drop('class', axis = 1).drop('train',axis=1)

    t = tree.DecisionTreeClassifier()
    t = t.fit(X, y)
#     print('depth', [i.tree_.max_depth for i in t.estimators_])
    y = data_test['class']
    X = data_test.drop('class', axis = 1).drop('train',axis=1)
    print(t.score(X,y))
    confusion_matrix = metrics.confusion_matrix(y, t.predict(X))
    print ("Confusion Matrix\n", confusion_matrix)
    err += t.score(X,y) / 10

print('Average score: ',err)

1.0
Confusion Matrix
 [[407   0]
 [  0 393]]
1.0
Confusion Matrix
 [[430   0]
 [  0 384]]
1.0
Confusion Matrix
 [[425   0]
 [  0 381]]
1.0
Confusion Matrix
 [[406   0]
 [  0 363]]
1.0
Confusion Matrix
 [[421   0]
 [  0 371]]
1.0
Confusion Matrix
 [[401   0]
 [  0 368]]
1.0
Confusion Matrix
 [[435   0]
 [  0 441]]
1.0
Confusion Matrix
 [[443   0]
 [  0 385]]
1.0
Confusion Matrix
 [[422   0]
 [  0 405]]
1.0
Confusion Matrix
 [[418   0]
 [  0 425]]
Average score:  1.0


In [94]:
with open("/home/dominik/Dokumenty/Studia/Data-mining/Lista5-trees/mushroom.dot", "w") as f:
    tree.export_graphviz(t, out_file=f, feature_names=X.columns)

In [95]:
clearedData['train'] = np.random.uniform(0, 1, len(clearedData))
err = 0
for i in range(10):
    data_test = clearedData[(clearedData['train'] >= i*0.1) & (clearedData['train'] < (i+1)*0.1)]
    data_train = clearedData[(clearedData['train'] < i*0.1) | (clearedData['train'] >= (i+1)*0.1)]

    y = data_train['class']
    X = data_train.drop('class', axis = 1).drop('train',axis=1)

    f = RandomForestClassifier()
    f = f.fit(X, y)
#     print('depth', [i.tree_.max_depth for i in t.estimators_])
    y = data_test['class']
    X = data_test.drop('class', axis = 1).drop('train',axis=1)
    print(f.score(X,y))
    confusion_matrix = metrics.confusion_matrix(y, f.predict(X))
    print ("Confusion Matrix\n", confusion_matrix)
    err += f.score(X,y) / 10

print('Average score: ',err)

1.0
Confusion Matrix
 [[413   0]
 [  0 398]]
1.0
Confusion Matrix
 [[420   0]
 [  0 423]]
1.0
Confusion Matrix
 [[425   0]
 [  0 412]]
1.0
Confusion Matrix
 [[418   0]
 [  0 370]]
1.0
Confusion Matrix
 [[470   0]
 [  0 373]]
1.0
Confusion Matrix
 [[419   0]
 [  0 377]]
1.0
Confusion Matrix
 [[412   0]
 [  0 404]]
1.0
Confusion Matrix
 [[419   0]
 [  0 361]]
1.0
Confusion Matrix
 [[433   0]
 [  0 415]]
1.0
Confusion Matrix
 [[379   0]
 [  0 383]]
Average score:  1.0
